services:
  db:
    image: postgres:15
    container_name: weather_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  main:
    build: .
    container_name: weather_main
    command: python main.py
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://weather:weatherpass@db:5432/weather_data

  current_data:
    build: .
    container_name: weather_current
    command: python current_data.py
    depends_on:
      - main
    environment:
      - DATABASE_URL=postgresql://weather:weatherpass@db:5432/weather_data

  dashboard:
    build: .
    container_name: weather_dashboard
    command: python -m streamlit run src/dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - current_data
    environment:
      - DATABASE_URL=postgresql://weather:weatherpass@db:5432/weather_data

volumes:
  postgres_data:
