name: Python CI

# Mikor fusson a workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Klónozzuk a repót
      - name: Checkout repository
        uses: actions/checkout@v3

      # Telepítsük a Python 3.11-et
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.2

      # Telepítsük a dependencies-t
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Lint with flake8
        run: |
          flake8 src tests

      - name: Check code style with black
        run: |
          black --check src tests

      # Futtassuk a teszteket
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest -v tests/
